CREATE TABLE dreams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date DATE NOT NULL,
  mood VARCHAR(255) NOT NULL,
  vibe VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  story TEXT NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  is_deleted BOOLEAN DEFAULT false
);
